# Generated by Django 4.2 on 2023-10-03 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('composteira', '0005_alter_composteira_tamanho_alter_composteira_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='composteira',
            name='regiao',
            field=models.CharField(choices=[('Norte', 'Norte'), ('Nordeste', 'Nordeste'), ('Sul', 'Sul'), ('Sudeste', 'Sudeste'), ('Centro-Oeste', 'Centro-Oeste')], max_length=12),
        ),
        migrations.AlterField(
            model_name='composteira',
            name='tamanho',
            field=models.CharField(choices=[('Pequena', 'Pequena'), ('Média', 'Média'), ('Grande', 'Grande')], max_length=7),
        ),
        migrations.AlterField(
            model_name='composteira',
            name='tipo',
            field=models.CharField(choices=[('Terra', 'Terra'), ('Caixa', 'Caixa')], max_length=5),
        ),
    ]
