# Generated by Django 4.2 on 2023-11-07 18:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('composteira', '0006_alter_composteira_regiao_alter_composteira_tamanho_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='composteira',
            name='usuario_idUsuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
