# Generated by Django 4.2 on 2023-11-07 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('composteira', '0008_rename_usuario_idusuario_composteira_fkusuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='composteira',
            name='com_minhoca',
        ),
    ]
