# Generated by Django 4.2 on 2023-11-17 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('composteira', '0011_compostagem_fkusuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compostagem',
            name='fkUsuario',
        ),
    ]
