# Generated by Django 4.2 on 2023-09-28 20:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Composteira',
            fields=[
                ('id_composteira', models.BigAutoField(primary_key=True, serialize=False)),
                ('com_minhoca', models.BooleanField(default=False, verbose_name='Com minhoca')),
                ('regiao', models.CharField(choices=[('1', 'Norte'), ('2', 'Nordeste'), ('3', 'Sul'), ('4', 'Sudeste'), ('5', 'Centro-Oeste')], max_length=12)),
                ('tamanho', models.CharField(choices=[('1', 'Pequena'), ('2', 'Média'), ('3', 'Grande')], max_length=7)),
                ('tipo', models.CharField(choices=[('1', 'Terra'), ('2', 'Caixa')], max_length=5)),
                ('data_construcao', models.DateField(verbose_name='Data construção')),
                ('nome', models.CharField(max_length=50)),
                ('usuario_idUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
        ),
    ]
