# Generated by Django 4.2 on 2023-09-28 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('composteira', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compostagem',
            fields=[
                ('id_compostagem', models.BigAutoField(primary_key=True, serialize=False)),
                ('data_inicio', models.DateField(verbose_name='Data colocado')),
                ('data_pronto', models.DateField(verbose_name='Data pronto')),
                ('peso', models.FloatField()),
                ('composteira_idComposteira', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='composteira.composteira', verbose_name='composteira')),
            ],
        ),
    ]
