# Generated by Django 4.2 on 2023-09-29 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('composteira', '0002_compostagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='composteira',
            name='regiao',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='composteira',
            name='tamanho',
            field=models.CharField(max_length=7),
        ),
        migrations.AlterField(
            model_name='composteira',
            name='tipo',
            field=models.CharField(max_length=5),
        ),
    ]
