# Generated by Django 4.2 on 2023-09-29 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('composteira', '0003_alter_composteira_regiao_alter_composteira_tamanho_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='composteira',
            name='regiao',
            field=models.CharField(choices=[('1', 'Norte'), ('2', 'Nordeste'), ('3', 'Sul'), ('4', 'Sudeste'), ('5', 'Centro-Oeste')], max_length=12),
        ),
    ]
