# Generated by Django 4.2 on 2023-09-29 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('composteira', '0004_alter_composteira_regiao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='composteira',
            name='tamanho',
            field=models.CharField(choices=[('1', 'Pequena'), ('2', 'Média'), ('3', 'Grande')], max_length=7),
        ),
        migrations.AlterField(
            model_name='composteira',
            name='tipo',
            field=models.CharField(choices=[('1', 'Terra'), ('2', 'Caixa')], max_length=5),
        ),
    ]
