# Generated by Django 4.2 on 2023-11-07 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('composteira', '0007_alter_composteira_usuario_idusuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='composteira',
            old_name='usuario_idUsuario',
            new_name='fkUsuario',
        ),
    ]
