# Generated by Django 4.2 on 2023-11-16 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('composteira', '0009_remove_composteira_com_minhoca'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compostagem',
            old_name='composteira_idComposteira',
            new_name='fkComposteira',
        ),
        migrations.RemoveField(
            model_name='compostagem',
            name='data_pronto',
        ),
    ]
