# Generated by Django 4.2 on 2023-11-17 19:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('composteira', '0010_rename_composteira_idcomposteira_compostagem_fkcomposteira_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compostagem',
            name='fkUsuario',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
